version: "3.9"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: intrusion-api

    ports:
      - "8000:8000"

    restart: unless-stopped


  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit

    container_name: intrusion-ui

    ports:
      - "8501:8501"

    depends_on:
      - api

    environment:
      API_URL: http://api:8000/predict_batch

    restart: unless-stopped